# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

local_conf_header:
  meta-read-only: |
    IMAGE_FEATURES:append = " read-only-rootfs overlayfs-etc"
    IMAGE_FEATURES:remove = " package-management"

    OVERLAYFS_ETC_MOUNT_POINT ?= "/mnt/etc"
    OVERLAYFS_ETC_FSTYPE ?= "ext4"
    OVERLAYFS_ETC_DEVICE ?= "/dev/mmcblk0p5"
