# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

local_conf_header:
  meta-tedge-container-plugin: |
    DISTRO_FEATURES:append = " virtualization"
    IMAGE_INSTALL:append = " docker-ce"
    IMAGE_INSTALL:append = " docker-compose"
    IMAGE_INSTALL:append = " tedge-container-plugin"
